import {
  Combine,
  Scissors,
  Minimize2,
  FileText,
  FileType2,
  FileImage,
  Images,
  RotateCw,
  Lock,
  Unlock,
  Stamp,
  Hash,
  Image as ImageIcon,
  Maximize,
  Crop,
  Replace,
  Eraser,
  Type,
  FlipHorizontal2,
  Binary,
  CaseSensitive,
  Pipette,
  QrCode,
  Link2,
  FileCode2,
  KeyRound,
  Braces,
  Code2,
  Pilcrow,
} from 'lucide-react'

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: null },
  { id: 'pdf', label: 'PDF Tools', icon: FileText },
  { id: 'image', label: 'Image Tools', icon: ImageIcon },
  { id: 'utility', label: 'Utilities', icon: Braces },
]

export const CATEGORY_LABELS = {
  pdf: 'PDF Tools',
  image: 'Image Tools',
  utility: 'Utilities',
}

// Central catalog. `component` maps to the key registered in tools/components.js
export const TOOLS = [
  // ---------- PDF TOOLS ----------
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    category: 'pdf',
    icon: Combine,
    description: 'Combine multiple PDFs into one document.',
    component: 'MergePdf',
    keywords: ['combine', 'join', 'pdf'],
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    category: 'pdf',
    icon: Scissors,
    description: 'Extract pages or split a PDF into separate files.',
    component: 'SplitPdf',
    keywords: ['extract', 'pages', 'separate'],
  },
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    category: 'pdf',
    icon: Minimize2,
    description: 'Reduce the file size of your PDF.',
    component: 'CompressPdf',
    keywords: ['reduce', 'size', 'shrink'],
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'pdf',
    icon: FileText,
    description: 'Convert a PDF into editable text you can copy.',
    component: 'PdfToWord',
    keywords: ['docx', 'convert', 'editable'],
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'pdf',
    icon: FileType2,
    description: 'Turn text or a DOCX into a clean PDF.',
    component: 'WordToPdf',
    keywords: ['docx', 'convert'],
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'pdf',
    icon: FileImage,
    description: 'Convert each PDF page into an image.',
    component: 'PdfToJpg',
    keywords: ['image', 'png', 'convert'],
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    category: 'pdf',
    icon: Images,
    description: 'Combine images into a single PDF.',
    component: 'JpgToPdf',
    keywords: ['image', 'png', 'convert'],
  },
  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'pdf',
    icon: RotateCw,
    description: 'Rotate all pages in a PDF document.',
    component: 'RotatePdf',
    keywords: ['turn', 'orientation'],
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    category: 'pdf',
    icon: Lock,
    description: 'Add password protection to a PDF.',
    component: 'ProtectPdf',
    keywords: ['password', 'encrypt', 'secure'],
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'pdf',
    icon: Unlock,
    description: 'Remove the password from a protected PDF.',
    component: 'UnlockPdf',
    keywords: ['password', 'decrypt', 'remove'],
  },
  {
    slug: 'watermark-pdf',
    name: 'Add Watermark',
    category: 'pdf',
    icon: Stamp,
    description: 'Stamp text onto every page of a PDF.',
    component: 'WatermarkPdf',
    keywords: ['stamp', 'overlay', 'brand'],
  },
  {
    slug: 'page-numbers-pdf',
    name: 'Add Page Numbers',
    category: 'pdf',
    icon: Hash,
    description: 'Insert page numbers into your PDF.',
    component: 'PageNumbersPdf',
    keywords: ['numbering', 'pages'],
  },

  // ---------- IMAGE TOOLS ----------
  {
    slug: 'compress-image',
    name: 'Compress Image',
    category: 'image',
    icon: Minimize2,
    description: 'Reduce image file size (JPG, PNG, WebP).',
    component: 'CompressImage',
    keywords: ['shrink', 'optimize', 'size'],
  },
  {
    slug: 'resize-image',
    name: 'Resize Image',
    category: 'image',
    icon: Maximize,
    description: 'Change image width and height.',
    component: 'ResizeImage',
    keywords: ['scale', 'dimensions'],
  },
  {
    slug: 'crop-image',
    name: 'Crop Image',
    category: 'image',
    icon: Crop,
    description: 'Crop to custom dimensions or aspect ratio.',
    component: 'CropImage',
    keywords: ['cut', 'trim'],
  },
  {
    slug: 'convert-image',
    name: 'Convert Image',
    category: 'image',
    icon: Replace,
    description: 'Convert between JPG, PNG, WebP and more.',
    component: 'ConvertImage',
    keywords: ['format', 'jpg', 'png', 'webp'],
  },
  {
    slug: 'remove-background',
    name: 'Remove Background',
    category: 'image',
    icon: Eraser,
    description: 'Erase a solid background from an image.',
    component: 'RemoveBackground',
    keywords: ['transparent', 'cutout'],
  },
  {
    slug: 'watermark-image',
    name: 'Add Watermark',
    category: 'image',
    icon: Type,
    description: 'Overlay text onto an image.',
    component: 'WatermarkImage',
    keywords: ['text', 'logo', 'brand'],
  },
  {
    slug: 'rotate-flip-image',
    name: 'Rotate / Flip Image',
    category: 'image',
    icon: FlipHorizontal2,
    description: 'Rotate by degrees or flip an image.',
    component: 'RotateFlipImage',
    keywords: ['mirror', 'turn'],
  },
  {
    slug: 'image-to-base64',
    name: 'Image to Base64',
    category: 'image',
    icon: Binary,
    description: 'Encode an image to a Base64 data URI.',
    component: 'ImageToBase64',
    keywords: ['encode', 'data uri'],
  },

  // ---------- UTILITIES ----------
  {
    slug: 'word-counter',
    name: 'Word Counter',
    category: 'utility',
    icon: Pilcrow,
    description: 'Count words, characters and sentences.',
    component: 'WordCounter',
    keywords: ['count', 'text', 'words'],
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    category: 'utility',
    icon: CaseSensitive,
    description: 'UPPERCASE, lowercase, Title Case and more.',
    component: 'CaseConverter',
    keywords: ['text', 'capitalize'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker',
    category: 'utility',
    icon: Pipette,
    description: 'Pick and convert HEX, RGB and HSL.',
    component: 'ColorPicker',
    keywords: ['hex', 'rgb', 'hsl'],
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'utility',
    icon: QrCode,
    description: 'Generate QR codes from text or URLs.',
    component: 'QrCodeGenerator',
    keywords: ['barcode', 'url'],
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder / Decoder',
    category: 'utility',
    icon: Link2,
    description: 'Encode or decode URL strings.',
    component: 'UrlEncoder',
    keywords: ['percent', 'escape'],
  },
  {
    slug: 'base64',
    name: 'Base64 Encode / Decode',
    category: 'utility',
    icon: FileCode2,
    description: 'Convert text to and from Base64.',
    component: 'Base64Tool',
    keywords: ['encode', 'decode'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    category: 'utility',
    icon: KeyRound,
    description: 'Generate strong, random passwords.',
    component: 'PasswordGenerator',
    keywords: ['random', 'secure'],
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    category: 'utility',
    icon: Braces,
    description: 'Prettify, minify and validate JSON.',
    component: 'JsonFormatter',
    keywords: ['pretty', 'validate', 'beautify'],
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML',
    category: 'utility',
    icon: Code2,
    description: 'Convert Markdown into HTML with a live preview.',
    component: 'MarkdownToHtml',
    keywords: ['md', 'convert', 'preview'],
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    category: 'utility',
    icon: Hash,
    description: 'Count characters with and without spaces.',
    component: 'CharacterCounter',
    keywords: ['count', 'letters'],
  },
]

export const getToolBySlug = (slug) => TOOLS.find((t) => t.slug === slug)

export const getToolsByCategory = (category) =>
  category === 'all' ? TOOLS : TOOLS.filter((t) => t.category === category)

// Return up to `count` related tools from the same category (excluding current).
export function getRelatedTools(slug, count = 4) {
  const tool = getToolBySlug(slug)
  if (!tool) return []
  const sameCategory = TOOLS.filter((t) => t.category === tool.category && t.slug !== slug)
  if (sameCategory.length >= count) return sameCategory.slice(0, count)
  const others = TOOLS.filter((t) => t.category !== tool.category).slice(0, count - sameCategory.length)
  return [...sameCategory, ...others]
}
